### ISSUE TITLE
Add arrival & departure dates to "Availability is not available." error message

### ISSUE THREAD

**Issue by milechukwu** [AustenR/PMTestingSuites#10]
To make it easier to figure out which test cases were skipped due to a lack of availability, could the test results include the attempted arrival date?  Maybe in a separate column?  Probably only the arrival is needed, not departure date, since the test name shows the duration of stay (right?)

Here is the sample output from one test that I'm trying to cross-check with the booking chart and then understand how many/which dates were successfully tested:

Site | Test | BaseRate | Tax | TotalRate | Deposit | Comments
-- | -- | -- | -- | -- | -- | --
GAL-Voyageur Full Service Cable | Peak (Weekday) | Fail | Fail | Fail | Fail | Availability is not available.

**Comment by AustenR** [comment]
Added arrival dates to the following error messages: 

**Availability is not available.**
**No rate found.**

added (arrival) to the end of each message
