### ISSUE TITLE
Exact Value Test - Peak  - Rental sites and 1-night tests will always fail

### ISSUE THREAD

**Issue by milechukwu** [AustenR/PMTestingSuites#9]
I'm opening this because I don't remember what we discussed about it months ago.  The peak season comes with a 2-night minimum for all rentals/accommodations on any day of the week.  But, the rate sheets show a "Weeknight" (1 night) rate because that rate does need to be available and working for last-minute bookings.

What can we do to prevent this test from appearing as a failure in regular rate tests? It should only be tested as part of last-minute booking tests.

**Comment by milechukwu** [comment]
Here is the example test result that brought this up for me:

Site | Test | Base Rate | Tax | Total Rate | Deposit | Comments
-- | -- | -- | -- | -- | -- | --
GAL-Rental Cabin | Peak (Weekday) | Fail | Fail | Fail | Fail | Staying   1 Night when a Minimum of 2 is Required.
GAL-Rental   Cabin | Peak (Weekday) | Fail | Fail | Fail | Fail | Staying 1 Night when a Minimum of 2 is   Required.
GAL-Rental Cabin | Peak (Weekday) | Fail | Fail | Fail | Fail | Staying   1 Night when a Minimum of 2 is Required.
GAL-Rental   Cabin | Peak (Weekday) | Fail | Fail | Fail | Fail | Staying 1 Night when a Minimum of 2 is   Required.

**Comment by AustenR** [comment]
Fixed 🥇
